config/routes.rb
Lovingspark::Application.routes.draw do
  resources :sparks

  root :to => 'welcome#index'

end

app/models/achievement.rb
class Spark < ActiveRecord::Base
has_attached_file :icon, :styles => { :small => "150x150>" },
                  :url  => "/assets/sparks/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/sparks/:id/:style/:basename.:extension"

validates_attachment_presence :icon
validates_attachment_size :icon, :less_than => 5.megabytes
validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png']
end

app/models/spark.rb
class Spark < ActiveRecord::Base
has_attached_file :icon, :styles => { :small => "150x150>" },
                  :url  => "/assets/sparks/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/sparks/:id/:style/:basename.:extension"

validates_attachment_presence :icon
validates_attachment_size :icon, :less_than => 5.megabytes
validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sparks_controller.rb
class SparksController < ApplicationController
  # GET /sparks
  # GET /sparks.json
  def index
    @sparks = Spark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sparks }
    end
  end

  # GET /sparks/1
  # GET /sparks/1.json
  def show
    @spark = Spark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spark }
    end
  end

  # GET /sparks/new
  # GET /sparks/new.json
  def new
    @spark = Spark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spark }
    end
  end

  # GET /sparks/1/edit
  def edit
    @spark = Spark.find(params[:id])
  end

  # POST /sparks
  # POST /sparks.json
  def create
    @spark = Spark.new(params[:spark])

    respond_to do |format|
      if @spark.save
        format.html { redirect_to @spark, notice: 'Spark was successfully created.' }
        format.json { render json: @spark, status: :created, location: @spark }
      else
        format.html { render action: "new" }
        format.json { render json: @spark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sparks/1
  # PUT /sparks/1.json
  def update
    @spark = Spark.find(params[:id])

    respond_to do |format|
      if @spark.update_attributes(params[:spark])
        format.html { redirect_to @spark, notice: 'Spark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sparks/1
  # DELETE /sparks/1.json
  def destroy
    @spark = Spark.find(params[:id])
    @spark.destroy

    respond_to do |format|
      format.html { redirect_to sparks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sparks_helper.rb
module SparksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lovingspark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topbar">
  <div class="topbar-inner">
    <div class="container-fluid">
      <a class="brand" href="#">LovingSpark</a>
      <%= tabs %>
    </div>
  </div>
</div>
<%= yield %>

app/views/sparks/_form.html.erb
<%= semantic_form_for @spark do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :name,   :hint => "Enter a title for this spark" %>
    <%= f.input :description, :hint => "Describe the spark" %>
    <%= f.input :points, :hint => "How many points is this spark worth?" %>
    <%= f.input :icon, :as => :file, :hint => "Select an image for this spark" %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button :button_html => {:class => "primary"} %>
  <% end %>
<% end %>

app/views/sparks/edit.html.erb
<h1>Editing Spark</h1>

<%= render 'form' %>

<a href="<%= spark_path %> " class="btn btn-small">Show</a>
<a href="<%= sparks_path %>" class="btn btn-small">Back</a>

app/views/sparks/index.html.erb
<h1>Listing Sparks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Points</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sparks.each do |spark| %>
  <tr>
    <td><%= spark.name %></td>
    <td><%= spark.description %></td>
    <td><%= spark.points %></td>
    <td><%= spark.completed? ? 'True' : 'False' %></td>
    <td><%= link_to 'Show', spark %></td>
    <td><%= link_to 'Edit', edit_spark_path(spark) %></td>
    <td><%= link_to 'Destroy', spark, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<a href="<%= new_spark_path %> " class="btn btn-small">New Spark</a>

app/views/sparks/new.html.erb
<h1>Create a new Spark</h1>

<%= render 'form' %>

<a href="<%= sparks_path %> " class="btn btn-small">Back</a>

app/views/sparks/show.html.erb
<%= image_tag @spark.icon.url(:small) %>

<p>
  <b>Name:</b>
  <%= @spark.name %>
</p>

<p>
  <b>Description:</b>
  <%= @spark.description %>
</p>

<p>
  <b>Points:</b>
  <%= @spark.points %>
</p>

<p>
  <b>Completed:</b>
  <%= @spark.completed %>
</p>

<br/>
<a href="<%= edit_spark_path(@spark) %> " class="btn btn-small">Edit</a>
<a href="<%= sparks_path %> " class="btn btn-small">Back</a>

app/views/welcome/index.html.erb
<h1>Welcome to LovingSpark</h1>
<h4>Spark something good</h4>